name: Backend CI Pipeline

on:
  push:
    branches: [ "main", "master", "pengujian" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    # Meminjam database MongoDB virtual dari GitHub untuk testing
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Install Dependencies
      run: npm install
      
    - name: Run Regression Tests & Coverage
      env:
        # Dummy Variables agar aplikasi tidak crash karena kehilangan .env
        MONGO_URI: mongodb://localhost:27017/testdb
        JWT_SECRET: testing_secret_123
        CLOUDINARY_CLOUD_NAME: dummy_cloud
        CLOUDINARY_API_KEY: dummy_key
        CLOUDINARY_API_SECRET: dummy_secret
        GEMINI_API_KEY: dummy_gemini_key
      # Mengubah perintah agar GitHub menampilkan tabel Code Coverage
      run: npm run test:coverage